export const FORGOT_PASSWORD_SEND = 'FORGOT_PASSWORD_SEND';
export const FORGOT_PASSWORD_SUCCESS_SET = 'FORGOT_PASSWORD_SUCCESS_SET';

export const RESET_PASSWORD_SEND = 'RESET_PASSWORD_SEND';
export const RESET_PASSWORD_SUCCESS_SET = 'RESET_PASSWORD_SUCCESS_SET';

export const PASSWORD_LOADER_SET = 'PASSWORD_LOADER_SET';
