export const USER_AUTH_STATUS_SET = 'USER_AUTH_STATUS_SET';

export const USER_GET = 'USER_GET';
export const USER_SET = 'USER_SET';

export const USER_LOADER_SET = 'USER_LOADER_SET';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const USER_EDIT = 'USER_EDIT';

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_LOADER_SET = 'PASSWORD_CHANGE_LOADER';
